basePath: /
definitions:
  models.AnimeDetailResponse:
    properties:
      anime_slug:
        type: string
      confidence_score:
        type: number
      cover:
        type: string
      details:
        $ref: '#/definitions/models.AnimeDetails'
      episode_list:
        items:
          $ref: '#/definitions/models.EpisodeListItem'
        type: array
      genre:
        items:
          type: string
        type: array
      judul:
        type: string
      message:
        type: string
      penonton:
        type: string
      rating:
        $ref: '#/definitions/models.AnimeRating'
      recommendations:
        items:
          $ref: '#/definitions/models.RecommendationItem'
        type: array
      sinopsis:
        type: string
      skor:
        type: string
      source:
        type: string
      status:
        type: string
      tipe:
        type: string
      url:
        type: string
    type: object
  models.AnimeDetails:
    properties:
      Duration:
        type: string
      English:
        type: string
      Japanese:
        type: string
      Producers:
        type: string
      'Released:':
        type: string
      Season:
        type: string
      Source:
        type: string
      Status:
        type: string
      Studio:
        type: string
      Total Episode:
        type: string
      Type:
        type: string
    type: object
  models.AnimeInfo:
    properties:
      genres:
        items:
          type: string
        type: array
      synopsis:
        type: string
      thumbnail_url:
        type: string
      title:
        type: string
    type: object
  models.AnimeRating:
    properties:
      score:
        type: string
      users:
        type: string
    type: object
  models.AnimeTerbaruItem:
    properties:
      anime_slug:
        type: string
      cover:
        type: string
      episode:
        type: string
      judul:
        type: string
      rilis:
        type: string
      uploader:
        type: string
      url:
        type: string
    type: object
  models.AnimeTerbaruResponse:
    properties:
      confidence_score:
        type: number
      data:
        items:
          $ref: '#/definitions/models.AnimeTerbaruItem'
        type: array
      message:
        type: string
      source:
        type: string
    type: object
  models.DayScheduleResponse:
    properties:
      confidence_score:
        type: number
      data:
        items:
          $ref: '#/definitions/models.ScheduleItem'
        type: array
      message:
        type: string
      source:
        type: string
    type: object
  models.DownloadLink:
    properties:
      provider:
        type: string
      url:
        type: string
    type: object
  models.DownloadLinksGroup:
    properties:
      MKV:
        additionalProperties:
          items:
            $ref: '#/definitions/models.DownloadLink'
          type: array
        type: object
      MP4:
        additionalProperties:
          items:
            $ref: '#/definitions/models.DownloadLink'
          type: array
        type: object
      x265 [Mode Irit Kuota tapi Kualitas Sama Beningnya]:
        additionalProperties:
          items:
            $ref: '#/definitions/models.DownloadLink'
          type: array
        type: object
    type: object
  models.EpisodeDetailResponse:
    properties:
      anime_info:
        $ref: '#/definitions/models.AnimeInfo'
      confidence_score:
        type: number
      download_links:
        $ref: '#/definitions/models.DownloadLinksGroup'
      message:
        type: string
      navigation:
        $ref: '#/definitions/models.EpisodeNavigation'
      other_episodes:
        items:
          $ref: '#/definitions/models.OtherEpisode'
        type: array
      release_info:
        type: string
      source:
        type: string
      streaming_servers:
        items:
          $ref: '#/definitions/models.StreamingServer'
        type: array
      thumbnail_url:
        type: string
      title:
        type: string
    type: object
  models.EpisodeListItem:
    properties:
      episode:
        type: string
      episode_slug:
        type: string
      release_date:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  models.EpisodeNavigation:
    properties:
      all_episodes_url:
        type: string
      next_episode_url:
        type: string
      previous_episode_url:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      confidence_score:
        type: number
      error:
        type: boolean
      message:
        type: string
    type: object
  models.HomeResponse:
    properties:
      confidence_score:
        type: number
      jadwal_rilis:
        $ref: '#/definitions/models.ScheduleData'
      message:
        type: string
      movies:
        items:
          $ref: '#/definitions/models.MovieItem'
        type: array
      new_eps:
        items:
          $ref: '#/definitions/models.NewEpisodeItem'
        type: array
      source:
        type: string
      top10:
        items:
          $ref: '#/definitions/models.Top10Item'
        type: array
    type: object
  models.MovieDetailItem:
    properties:
      anime_slug:
        type: string
      cover:
        type: string
      genres:
        items:
          type: string
        type: array
      judul:
        type: string
      sinopsis:
        type: string
      skor:
        type: string
      status:
        type: string
      tanggal:
        type: string
      url:
        type: string
      views:
        type: string
    type: object
  models.MovieItem:
    properties:
      anime_slug:
        type: string
      cover:
        type: string
      genres:
        items:
          type: string
        type: array
      judul:
        type: string
      tanggal:
        type: string
      url:
        type: string
    type: object
  models.MovieResponse:
    properties:
      confidence_score:
        type: number
      data:
        items:
          $ref: '#/definitions/models.MovieDetailItem'
        type: array
      message:
        type: string
      source:
        type: string
    type: object
  models.NewEpisodeItem:
    properties:
      anime_slug:
        type: string
      cover:
        type: string
      episode:
        type: string
      judul:
        type: string
      rilis:
        type: string
      url:
        type: string
    type: object
  models.OtherEpisode:
    properties:
      release_date:
        type: string
      thumbnail_url:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  models.RecommendationItem:
    properties:
      anime_slug:
        type: string
      cover_url:
        type: string
      episode:
        type: string
      rating:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  models.ScheduleData:
    properties:
      Friday:
        items:
          $ref: '#/definitions/models.ScheduleItem'
        type: array
      Monday:
        items:
          $ref: '#/definitions/models.ScheduleItem'
        type: array
      Saturday:
        items:
          $ref: '#/definitions/models.ScheduleItem'
        type: array
      Sunday:
        items:
          $ref: '#/definitions/models.ScheduleItem'
        type: array
      Thursday:
        items:
          $ref: '#/definitions/models.ScheduleItem'
        type: array
      Tuesday:
        items:
          $ref: '#/definitions/models.ScheduleItem'
        type: array
      Wednesday:
        items:
          $ref: '#/definitions/models.ScheduleItem'
        type: array
    type: object
  models.ScheduleItem:
    properties:
      anime_slug:
        type: string
      cover_url:
        type: string
      genres:
        items:
          type: string
        type: array
      release_time:
        type: string
      score:
        type: string
      title:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
  models.ScheduleResponse:
    properties:
      confidence_score:
        type: number
      data:
        $ref: '#/definitions/models.ScheduleData'
      message:
        type: string
      source:
        type: string
    type: object
  models.SearchResponse:
    properties:
      confidence_score:
        type: number
      data:
        items:
          $ref: '#/definitions/models.SearchResultItem'
        type: array
      message:
        type: string
      source:
        type: string
    type: object
  models.SearchResultItem:
    properties:
      anime_slug:
        type: string
      cover:
        type: string
      genre:
        items:
          type: string
        type: array
      judul:
        type: string
      penonton:
        type: string
      sinopsis:
        type: string
      skor:
        type: string
      status:
        type: string
      tipe:
        type: string
      url:
        type: string
    type: object
  models.StreamingServer:
    properties:
      server_name:
        type: string
      streaming_url:
        type: string
    type: object
  models.Top10Item:
    properties:
      anime_slug:
        type: string
      cover:
        type: string
      genres:
        items:
          type: string
        type: array
      judul:
        type: string
      rating:
        type: string
      url:
        type: string
    type: object
host: localhost:8002
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API web scraping untuk mengambil data dari situs Winbu.TV
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Winbu.TV Web Scraping API
  version: "1.0"
paths:
  /api/v1/anime-detail:
    get:
      consumes:
      - application/json
      description: Mengambil detail anime, film, atau series termasuk episode, sinopsis,
        dan rekomendasi. Slug dapat berupa 'nama-anime', 'film/nama-film', atau 'series/nama-series'
      parameters:
      - description: 'Anime/Movie/Series slug (contoh: ''kobane-2022'', ''film/kobane-2022'',
          ''series/legend-of-the-female-general'')'
        in: query
        name: anime_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AnimeDetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get anime/movie/series detail
      tags:
      - Detail
  /api/v1/anime-terbaru:
    get:
      consumes:
      - application/json
      description: Mengambil daftar anime terbaru dengan pagination
      parameters:
      - default: 1
        description: Nomor halaman
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AnimeTerbaruResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get anime terbaru
      tags:
      - Anime
  /api/v1/episode-detail:
    get:
      consumes:
      - application/json
      description: Mengambil detail episode termasuk server streaming dan link download
      parameters:
      - description: URL episode
        in: query
        name: episode_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EpisodeDetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get episode detail
      tags:
      - Detail
  /api/v1/home:
    get:
      consumes:
      - application/json
      description: Mengambil data homepage termasuk top 10 anime, episode terbaru,
        film terbaru, dan jadwal rilis
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HomeResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get homepage data
      tags:
      - Homepage
  /api/v1/jadwal-rilis:
    get:
      consumes:
      - application/json
      description: Mengambil jadwal rilis anime per hari
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ScheduleResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get jadwal rilis
      tags:
      - Schedule
  /api/v1/jadwal-rilis/{day}:
    get:
      consumes:
      - application/json
      description: Mengambil jadwal rilis anime untuk hari tertentu
      parameters:
      - description: Nama hari (monday, tuesday, wednesday, thursday, friday, saturday,
          sunday)
        in: path
        name: day
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DayScheduleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get jadwal rilis by day
      tags:
      - Schedule
  /api/v1/movie:
    get:
      consumes:
      - application/json
      description: Mengambil daftar film dengan pagination
      parameters:
      - default: 1
        description: Nomor halaman
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MovieResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get movies
      tags:
      - Movies
  /api/v1/search:
    get:
      consumes:
      - application/json
      description: Mencari anime berdasarkan judul
      parameters:
      - description: Query pencarian
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SearchResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Search anime
      tags:
      - Search
schemes:
- http
- https
swagger: "2.0"
